/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRelayer,
  IRelayerInterface,
} from "../../../../src/contracts/interfaces/IRelayer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "relayer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "metaTx",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "MetaTransactionSubmitted",
    type: "event",
  },
  {
    inputs: [],
    name: "getRelayerFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "metaTx",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "submitMetaTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRelayer__factory {
  static readonly abi = _abi;
  static createInterface(): IRelayerInterface {
    return new Interface(_abi) as IRelayerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRelayer {
    return new Contract(address, _abi, runner) as unknown as IRelayer;
  }
}
