/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZKVerifier,
  IZKVerifierInterface,
} from "../../../../src/contracts/interfaces/IZKVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "publicSignals",
        type: "bytes32[]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZKVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZKVerifierInterface {
    return new Interface(_abi) as IZKVerifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IZKVerifier {
    return new Contract(address, _abi, runner) as unknown as IZKVerifier;
  }
}
