/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IRelayerInterface extends Interface {
  getFunction(
    nameOrSignature: "getRelayerFee" | "submitMetaTransaction"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MetaTransactionSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRelayerFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMetaTransaction",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRelayerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitMetaTransaction",
    data: BytesLike
  ): Result;
}

export namespace MetaTransactionSubmittedEvent {
  export type InputTuple = [
    relayer: AddressLike,
    metaTx: BytesLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [relayer: string, metaTx: string, fee: bigint];
  export interface OutputObject {
    relayer: string;
    metaTx: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRelayer extends BaseContract {
  connect(runner?: ContractRunner | null): IRelayer;
  waitForDeployment(): Promise<this>;

  interface: IRelayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRelayerFee: TypedContractMethod<[], [bigint], "view">;

  submitMetaTransaction: TypedContractMethod<
    [metaTx: BytesLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRelayerFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitMetaTransaction"
  ): TypedContractMethod<
    [metaTx: BytesLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MetaTransactionSubmitted"
  ): TypedContractEvent<
    MetaTransactionSubmittedEvent.InputTuple,
    MetaTransactionSubmittedEvent.OutputTuple,
    MetaTransactionSubmittedEvent.OutputObject
  >;

  filters: {
    "MetaTransactionSubmitted(address,bytes,uint256)": TypedContractEvent<
      MetaTransactionSubmittedEvent.InputTuple,
      MetaTransactionSubmittedEvent.OutputTuple,
      MetaTransactionSubmittedEvent.OutputObject
    >;
    MetaTransactionSubmitted: TypedContractEvent<
      MetaTransactionSubmittedEvent.InputTuple,
      MetaTransactionSubmittedEvent.OutputTuple,
      MetaTransactionSubmittedEvent.OutputObject
    >;
  };
}
