/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ZKVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isProofVerified"
      | "markProofAsVerified"
      | "verificationKey"
      | "verifiedProofs"
      | "verifyProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isProofVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markProofAsVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "isProofVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markProofAsVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export interface ZKVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): ZKVerifier;
  waitForDeployment(): Promise<this>;

  interface: ZKVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isProofVerified: TypedContractMethod<[proof: BytesLike], [boolean], "view">;

  markProofAsVerified: TypedContractMethod<
    [proof: BytesLike],
    [void],
    "nonpayable"
  >;

  verificationKey: TypedContractMethod<[], [string], "view">;

  verifiedProofs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyProof: TypedContractMethod<
    [proof: BytesLike, publicSignals: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isProofVerified"
  ): TypedContractMethod<[proof: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markProofAsVerified"
  ): TypedContractMethod<[proof: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifiedProofs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [proof: BytesLike, publicSignals: BytesLike[]],
    [boolean],
    "view"
  >;

  filters: {};
}
